/*
 * Copyright 2024 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package commands

import (
	"context"
	"os"

	"github.com/mrlyc/inu/pkg/anonymizer"
	"github.com/mrlyc/inu/pkg/cli"
	"github.com/rotisserie/eris"
	"github.com/spf13/cobra"
)

var (
	restoreFile     string
	restoreContent  string
	restoreEntities string
	restoreNoPrint  bool
	restoreOutput   string
)

// NewRestoreCmd creates the restore command.
func NewRestoreCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore anonymized text to original",
		Long: `Restore anonymized text using the entities file saved during anonymization.
Requires an entities YAML file generated by the anonymize command.`,
		RunE: runRestore,
	}

	flags := cmd.Flags()
	flags.StringVarP(&restoreFile, "file", "f", "", "Read anonymized text from file")
	flags.StringVarP(&restoreContent, "content", "c", "", "Anonymized text as string")
	flags.StringVarP(&restoreEntities, "entities", "e", "", "Entities YAML file (required)")
	flags.BoolVar(&restoreNoPrint, "no-print", false, "Do not print output to stdout (default: print to stdout)")
	flags.StringVarP(&restoreOutput, "output", "o", "", "Write restored text to file")

	_ = cmd.MarkFlagRequired("entities")

	return cmd
}

func runRestore(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Validate entities flag
	if restoreEntities == "" {
		return eris.New("--entities flag is required")
	}

	// Read input
	var stdin *os.File
	if restoreFile == "" && restoreContent == "" {
		stdin = os.Stdin
	}

	input, err := cli.ReadInput(restoreFile, restoreContent, stdin)
	if err != nil {
		return err
	}

	// Load entities
	cli.ProgressMessage("=== Loading entities from: %s ===", restoreEntities)
	entities, err := cli.LoadEntitiesFromYAML(restoreEntities)
	if err != nil {
		return err
	}

	// Initialize LLM (not needed for restore, but keep same pattern)
	llm, err := anonymizer.CreateOpenAIChatModel(ctx)
	if err != nil {
		return err
	}

	anon, err := anonymizer.NewHashHidePair(llm)
	if err != nil {
		return err
	}

	// Restore text
	cli.ProgressMessage("=== Restoring text... ===")
	result, err := anon.RestoreText(ctx, entities, input)
	if err != nil {
		return err
	}

	// Output restored text
	if err := cli.WriteOutput(result, restoreNoPrint, restoreOutput); err != nil {
		return err
	}

	cli.ProgressMessage("=== Restoration complete ===")
	return nil
}
