run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  goimports:
    local-prefixes: github.com/mrlyc/inu

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
